<?php
// module/Application/view/application/index/search.phtml:

$title = 'Search Email';
$this->headTitle($title);
?>
<head>
    <style>
        h1
        {
            text-align: center;
        }
        .add_new{
            position: absolute;
            top: 100px;
            right: 50px;

        }
        a:link{color:red;}

        a:visited{color:#ff6c0e;}

        a:hover{color:pink;}

        a:active{color:#ccc;}

        .table {
            width: 70%;
            margin: 40px auto;
        }
        table {
            border-spacing: 0;
            width: 100%;
        }
        tr {
            text-align: center;
        }
        th {
            padding: 10px;
        }
        table tbody tr:nth-child(odd){
            background-color: #eee
        }
        table thead {
            background-color: #ff6c0e;
            color: white;
        }
        table thead th:first-child {
            border-radius: 5px 0 0 0;
            border: 1px solid #ff6c0e;
        }
        table thead th:last-child {
            border-radius: 0 5px 0 0;
            border-right: 1px solid #ff6c0e;
        }
        table tbody tr:last-child td:first-child {
            border-radius: 0 0 0 5px;
        }

        table tbody tr:last-child td:last-child {
            border-radius: 0 0 5px 0;
        }




        #search-box {
            width: 100%;
            margin: 0;

        }

        #search-form
        {

            position: absolute;
            top: 100px;
            right: 200px;
            height: 25px;
            width: 220px;
            border: 1px solid #999;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            background-color: #fff;
            overflow: hidden;
        }

        #search-text
        {
            font-size: 14px;
            color: #ddd;
            border-width: 0;
            background: transparent;
        }

        #search-box input[type="text"]
        {
            width: 90%;
            padding: 5px 0 12px 1em;
            color: #333;
            outline: none;
        }

        #search-button {
            position: absolute;
            top: 0;
            right: 0;
            height: 25px;
            width: 80px;
            font-size: 14px;
            color: #fff;
            text-align: center;

            border-width: 0;
            background-color:#ff6c0e;

            cursor: pointer;
        }


    </style>
</head>
<h1 ><?= $this->escapeHtml($title) ?></h1>

<div id='search-box' class='form'>
    <div id='search-form' method='post' target='_top'>
        <input id="search-text"  placeholder='Search' type="text"/>
        <button onclick="jump()" id='search-button'>
            <span>Search</span>
        </button>
    </div>
</div>
<a class="add_new" href="<?= $this->url('email', ['action' => 'add']) ?>">Add new Email</a>


<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Email</th>

    </tr>
    </thead>

    <?php foreach ($emails as $email) : ?>
        <tr>
            <td><?= $this->escapeHtml($email->uid) ?></td>
            <td><?= $this->escapeHtml($email->name) ?></td>
            <td><?= $this->escapeHtml($email->email_string) ?></td>

        </tr>
    <?php endforeach; ?>
</table>
<script>
    function jump(){
        const obj = document.getElementById("search-text");
        if(obj.value ==""){
            alert("You have not input anything!");
        }
        else if(!/^[0-9]*$/.test(obj.value)){
            alert("Please input an Integer");
        }
        else{
            const s = document.getElementById('search-text');
            window.location.href='/email/search/' + encodeURI(s.value);
        }
    }
    const tt = document.getElementById('search-text');
    tt.addEventListener("keyup", function(event) {
        if (event.key === 'Enter') {
            jump();
        }
    });

</script>